

import {
    Mailbox, Package, Plane, Truck, Zap, Building2, Building, MapPin, Globe,
    Search, Plus, Download, Check, CircleCheck, TriangleAlert, OctagonX, X,
    ChevronDown, ChevronRight, ArrowRight, ArrowLeft, Bell, Clock, RefreshCw,
    Pencil, Save, Scale, Ruler, User, IdCard, Handshake, CreditCard, Wallet,
    Sparkles, Compass, House, LogOut, Languages, Volume2, VolumeX, Type, Contrast,
    Phone, Info, CircleHelp, Receipt, ClipboardList, FileText, QrCode, Inbox,
    Flag, Target, Pin, ShieldCheck, Camera, Fingerprint, ListChecks, Upload,
} from 'lucide-vue-next';

export const ICONS = {

    mailbox: Mailbox,
    package: Package,
    plane: Plane,
    truck: Truck,
    zap: Zap,
    office: Building2,
    building: Building,
    mappin: MapPin,
    pin: Pin,
    globe: Globe,
    receipt: Receipt,
    clipboard: ClipboardList,
    file: FileText,
    qr: QrCode,
    inbox: Inbox,
    flag: Flag,
    target: Target,

    search: Search,
    plus: Plus,
    download: Download,
    upload: Upload,
    check: Check,
    x: X,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'arrow-right': ArrowRight,
    'arrow-left': ArrowLeft,
    bell: Bell,
    clock: Clock,
    refresh: RefreshCw,
    edit: Pencil,
    save: Save,
    scale: Scale,
    ruler: Ruler,
    sparkles: Sparkles,
    compass: Compass,
    home: House,
    logout: LogOut,
    languages: Languages,
    volume: Volume2,
    'volume-x': VolumeX,
    type: Type,
    contrast: Contrast,
    phone: Phone,
    info: Info,
    help: CircleHelp,

    user: User,
    'id-card': IdCard,
    handshake: Handshake,
    card: CreditCard,
    money: Wallet,
    shield: ShieldCheck,
    camera: Camera,
    fingerprint: Fingerprint,
    checks: ListChecks,

    'circle-check': CircleCheck,
    'triangle-alert': TriangleAlert,
    'octagon-x': OctagonX,
};
